console.log("✖ some assertion (12.3ms)");
console.log("");
console.log("✖ failing tests:");
console.log("");
console.log("✖ some assertion (12.3ms)");
console.log("✖ another assertion (5.1ms)");
console.log("");
console.log("ℹ tests 4");
console.log("ℹ pass 2");
console.log("ℹ fail 2");
console.log("ℹ duration_ms 88");
process.exit(1);
